on:
  push:
    branches: ["main"]

jobs:
  deploy-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: yuzhiyongcn/setup-maven@v1.0.0
      - uses: actions/setup-java@v1.4.4
        with: 
          destribution: 'oracle'
          java-version: '19'
      - run: mvn clean install
        env:
          CI: ""
      run: |
        docker build -t ammarabuyaman/fsm4j .
        docker login -u ammarabuyaman -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push ammarabuyaman/fsm4j
      
          
      
    
